import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper";


export const metadata: Metadata = {
  title: "ArtistryHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  return (
  <html lang="en">
    <body className="antialiased">
      {children}
    </body>
  </html>
  );
}
